INSERT INTO FITNESS_CENTAR (ADDRESS , E_MAIL_OF_CENTAR , NAME , NUMBER_OF_CENTAR ) VALUES ('Blue street 6372', 'active@gmail.com', 'Active', '86947394' )
INSERT INTO FITNESS_CENTAR (ADDRESS , E_MAIL_OF_CENTAR , NAME , NUMBER_OF_CENTAR ) VALUES ('Red street 672', 'strong@gmail.com', 'Strong fit', '79977394' )
INSERT INTO FITNESS_CENTAR (ADDRESS , E_MAIL_OF_CENTAR , NAME , NUMBER_OF_CENTAR ) VALUES ('Big street 7', 'fit@gmail.com', 'Fit fit', '89690' )

INSERT INTO WORKOUT (NAME , DESCRIPTION , TYPE_OF_WORKOUT , WORKOUT_DURATION , COACH_ID ) VALUES('Chest workout', 'One hour of chest workout', 'group workout', '60', '2')
INSERT INTO WORKOUT (NAME , DESCRIPTION , TYPE_OF_WORKOUT , WORKOUT_DURATION , COACH_ID ) VALUES('Leg day', 'short workout but strong', 'personal workout', '35', '5')

INSERT INTO HALL (ID , CAPACITY , FITNESS_CENTAR_ID  ) VALUES('5', '20', '2')
INSERT INTO HALL (ID , CAPACITY , FITNESS_CENTAR_ID  ) VALUES('2', '10', '3')
